### ISSUE TITLE
PSP games not running as good on 04-02-24 update compared to 02-23-24 update

### ISSUE THREAD

**Issue by joeykala** [AeolusUX/R36S-DTB#2]
Not sure why, but using the same sd cards, same config files, same exact settings, same everything. PSP games on the april ARKOS update are not running as smooth as compared to the February update. Do you know why and if there's a fix to this? On the R36s. Thank you!

**Comment by AeolusUX** [comment]
Can you give the exact emulator/core and the game so I can try and recreate on my side?

**Comment by joeykala** [comment]
god of war chains of olympus. Emulator Default standalone. Core Default. This is from me hitting select and edit this games meta data. It doesn't let me view the actual core and change it. unless you know the other way to do it.

**Comment by AeolusUX** [comment]
This game plays better in the ppsspp standalone 2021 core. Have you tried that?

**Comment by joeykala** [comment]
yeah it was the same thing. No difference to be honest. But, do you know how to enable full screen on standalone 2021?

**Comment by AeolusUX** [comment]
I just tried with a 02232024 flash and a 04022024 one and both works the same. I wonder what else is different from your device.

**Comment by joeykala** [comment]
yeah im not sure. I even flashed the 02232024 on another r36, added my settings, and god of war is still running at fps 20. No clue as to why with the new update it doesn't perform as well. Very weird. But thank you for your help!

**Comment by joeykala** [comment]
it looks like every psp game not only god of war, is +10 fps on my 02232024 consoles compared to the new april ones. Very weird.
