### ISSUE TITLE
DTB-File (Original Screen)

### ISSUE THREAD

**Issue by Murderhead** [AeolusUX/R36S-DTB#3]
My "rk3326-r35s-linux.dtb.V1" is not recognized by the [Tool](https://aeolusux.github.io/ArkOS-R3XS/tools/dtbIdentify.htm)

**Comment by AeolusUX** [comment]
Did it say in the tool to upload rk3326-r35s-linux.dtb.V1?

**Comment by Murderhead** [comment]
> rk3326-r35s-linux.dtb

Also not recognized if I upload it as "rk3326-r35s-linux.dtb"

**The uploaded data does not match the content of any pre-existing file.**

**Comment by AeolusUX** [comment]
They're not the same. It's not gonna magically work if you changed the name. You'd need the non .v1 File.

**Comment by Murderhead** [comment]
Thanks, know I finally know my old TF-Card Image Backup got corrupted through the backup Process. Because I don't have the original "rk3326-r35s-linux.dtb" file on the "BOOT" partition.
