### ISSUE TITLE
New R36S screen v5

### ISSUE THREAD

**Issue by chronoss09** [AeolusUX/R36S-DTB#4]
https://www.mediafire.com/file/c6siul1y49giyf2/R36S_V5_screen.zip/file

**Comment by AeolusUX** [comment]
What's this? This is panel 4.

**Comment by chronoss09** [comment]
but on my console, there is a text file name "R36S V5.txt", that why i shre this file for backup.

**Comment by obiwan-bartek** [comment]
Hi, @AeolusUX 
My R36s just arrived, and it have exact the same "rk3326-r35s-linux.dtb" as in the first post. Your tool recognizes it as Panel 4.
But it is different than "rk3326-r35s-linux.dtb" from your repository from Panel 4 folder (which in fact is NOT recognized by your tool at all - weird). Why is that? Can you integrate "rk3326-r35s-linux.dtb" from the first post in your repository also? What is the difference between "your" panel 4 DTB and "ours"?

**Comment by AeolusUX** [comment]
> Hi, @AeolusUX My R36s just arrived, and it have exact the same "rk3326-r35s-linux.dtb" as in the first post. Your tool recognizes it as Panel 4. But it is different than "rk3326-r35s-linux.dtb" from your repository from Panel 4 folder (which in fact is NOT recognized by your tool at all - weird). Why is that? Can you integrate "rk3326-r35s-linux.dtb" from the first post in your repository also? What is the difference between "your" panel 4 DTB and "ours"?

They are the same even if you try them both they both work. I just changed something on mine to track if it was replaced from the default one which you have.

**Comment by obiwan-bartek** [comment]
Oh, I see. OK. Will you put the original file along with that one you modified for preservation purposes?
