### ISSUE TITLE
Flashed SD card for panel 4, screen not recognized 

### ISSUE THREAD

**Issue by Superflamingo2145** [AeolusUX/R36S-DTB#7]
I just flashed an SD card with the panel 4 OS, it ran through the initial boot screens and now my screen just has a black background with 4 white odd lines that go through the middle. 2 of the lines say voltage and the other 2 I can't make out what they say. R36S, stamped for June 2024, rk3326-r35s-linux file says panel 4 when using the tool. doesn't seem to work.

**Comment by AeolusUX** [comment]
Charge your device
